version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - '8000:8000'
    container_name: web-stadium
    command: bash -c 'python manage.py migrate && python manage.py create_timeframes && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
    networks:
      - stadium_network

  db:
    image: mysql:5.7
    container_name: stadium-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stadium
      MYSQL_USER: stadium
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - ./db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - stadium_network
networks:
  stadium_network:
  
