# Generated by Django 3.1.7 on 2021-03-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0002_auto_20210322_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
