# Generated by Django 3.1.7 on 2021-05-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0002_auto_20210518_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='StarRating',
        ),
    ]
