# Generated by Django 3.1.7 on 2021-03-25 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0003_auto_20210324_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
