# Generated by Django 3.1.7 on 2021-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0004_auto_20210520_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='starrating',
            name='can_rate',
            field=models.BooleanField(default=True),
        ),
    ]
