# Generated by Django 3.1.7 on 2021-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0009_auto_20210326_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
