# Generated by Django 3.1.7 on 2021-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0015_auto_20210329_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
