# Generated by Django 3.1.7 on 2021-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0024_auto_20210331_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumtimeframe',
            name='field_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
