# Generated by Django 3.1.7 on 2021-04-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0026_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiumtimeframe',
            name='field_count',
        ),
    ]
