# Generated by Django 3.1.7 on 2021-04-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0029_auto_20210406_1602'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
