# Generated by Django 3.1.7 on 2021-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0033_auto_20210408_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default='<function now at 0x0000016904687280>'),
        ),
    ]
