# Generated by Django 3.1.7 on 2021-04-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0035_auto_20210408_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pitch_clothes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='type_stadium',
            field=models.CharField(choices=[('7players', 'Sân 7'), ('11players', 'sân 11')], default='7players', max_length=30),
        ),
    ]
