# Generated by Django 3.1.7 on 2021-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0037_auto_20210423_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='field_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
