# Generated by Django 3.1.7 on 2021-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0038_auto_20210423_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_stadium',
            field=models.CharField(choices=[('7players', 'Sân 7'), ('11players', 'Sân 11')], default='7players', max_length=30),
        ),
    ]
