# Generated by Django 3.1.7 on 2021-04-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0039_auto_20210423_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='three_field_merge',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='three_field_merge_display',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
