# Generated by Django 3.1.7 on 2021-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0040_auto_20210426_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='three_field_merge_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
