# Generated by Django 3.1.7 on 2021-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0044_auto_20210505_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumtimeframe',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
