# Generated by Django 3.1.7 on 2021-05-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0045_stadiumtimeframe_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_stadium.stadium'),
        ),
        migrations.DeleteModel(
            name='StadiumComment',
        ),
    ]
