# Generated by Django 3.1.7 on 2021-05-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_stadium', '0046_auto_20210506_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_stadium.stadium'),
        ),
    ]
